### ISSUE TITLE
Setting a local path for the recording file

### ISSUE THREAD

**Issue by jonnYyYyYy** [hbk-world/ghs-gendaqapi-python#19]
Hey guys, is it possible to set the storage location to a desired path on my local PC?

**Comment by dduraesdebarros** [comment]
Hello @jonnYyYyYy. Unfortunately no. Currently we only offer support for setting the storage location via **ghs_set_storage_location**. If you choose Remote Storage (your local pc), the chosen storage path defined in Perception would be used. Hope this helps.
